%% Gamma local analysis - Egreedy
clear
[model, sim, env ] = games.get(2,1);
truegamma=0.5;
truealpha=0.2;
trueepsilon=0.1;
agent = agents.discrete.get('sarsa',env.numstates,env.numactions,'policytype','egreedy','epsilon',trueepsilon,'gamma',truegamma,'alpha',truealpha);
[ trace policytrace ] = analyse.sampling.synthetic_traces( agent, sim, 300 );
gammas=linspace(0,1,100);
parfor i=1:100
    agent = agents.discrete.get('sarsa',env.numstates,env.numactions,'policytype','egreedy','epsilon',trueepsilon,'gamma',gammas(i),'alpha',truealpha);
    score(i) = agent.imitate_run(trace);
end
plot(gammas,exp(score));
title(sprintf('Likelihood of a trace with gamma %.1f,epsilon %.1f being generated by gamma x',truegamma,trueepsilon))
xlabel('Gammas')
ylabel('Pr(trace)')
saveas(gcf,sprintf('img\\gamma_egreedy.jpg'));
%% Gamma local analysis - Softmax
clear
[model, sim, env ] = games.get(2,1);
truegamma=0.5;
truealpha=0.05;
truetemperature=10;
agent = agents.discrete.get('sarsa',env.numstates,env.numactions,'policytype','softmax','temperature',truetemperature,'gamma',truegamma,'alpha',truealpha);
[ trace policytrace ] = analyse.sampling.synthetic_traces( agent, sim, 300 );
gammas=linspace(0,1,100);
for i=1:100
    agent = agents.discrete.get('sarsa',env.numstates,env.numactions,'policytype','softmax','temperature',truetemperature,'gamma',gammas(i),'alpha',truealpha);
    score(i) = agent.imitate_run(trace);
end
plot(gammas,exp(score));
title(sprintf('Likelihood of a trace with gamma 0.5,temperature %.1f being generated by gamma x',truetemperature))
xlabel('Gammas')
ylabel('Pr(trace)')
saveas(gcf,sprintf('img\\gamma_softmax.jpg'));
%% Epsilon local analysis
clear
[model, sim, env ] = games.get(2,1);
truegamma=0.5;
truealpha=0.2;
trueepsilon=0.1;
agent = agents.discrete.get('sarsa',env.numstates,env.numactions,'policytype','egreedy','epsilon',trueepsilon,'gamma',truegamma,'alpha',truealpha);
[ trace policytrace ] = analyse.sampling.synthetic_traces( agent, sim, 300 );
epsilons=linspace(0,1,100);
parfor i=1:100
    agent = agents.discrete.get('sarsa',env.numstates,env.numactions,'policytype','egreedy','epsilon',epsilons(i),'gamma',truegamma,'alpha',truealpha);
    score(i) = agent.imitate_run(trace);
end
plot(epsilons,exp(score));
title(sprintf('Likelihood of a trace with gamma %.1f,epsilon %.1f being generated by epsilon x',truegamma,trueepsilon))
xlabel('Epsilons')
ylabel('Pr(trace)')
saveas(gcf,sprintf('img\\epsilon.jpg'));
%% Temperature local analysis 
clear
[model, sim, env ] = games.get(2,1);
truegamma=0.5;
truealpha=0.2;
truetemperature=10;
agent = agents.discrete.get('sarsa',env.numstates,env.numactions,'policytype','softmax','temperature',truetemperature,'gamma',truegamma,'alpha',truealpha);
[ trace policytrace ] = analyse.sampling.synthetic_traces( agent, sim, 300 );
temperatures=linspace(5,50,100);
parfor i=1:100
    agent = agents.discrete.get('sarsa',env.numstates,env.numactions,'policytype','softmax','temperature',temperatures(i),'gamma',truegamma,'alpha',truealpha);
    score(i) = agent.imitate_run(trace);
end
plot(temperatures,exp(score));
title(sprintf('Likelihood of a trace with gamma %.1f,temperature %.1f being generated by temperature x',truegamma,truetemperature))
xlabel('Temperatures')
ylabel('Pr(trace)')
saveas(gcf,sprintf('img\\temperatures.jpg'));
%% Alpha local analysis - Egreedy
clear
[model, sim, env ] = games.get(2,1);
truegamma=0.5;
truealpha=0.2;
trueepsilon=0.1;
agent = agents.discrete.get('sarsa',env.numstates,env.numactions,'policytype','egreedy','epsilon',trueepsilon,'gamma',truegamma,'alpha',truealpha);
[ trace policytrace ] = analyse.sampling.synthetic_traces( agent, sim, 300 );
alphas=linspace(0,1,100);
parfor i=1:100
    agent = agents.discrete.get('sarsa',env.numstates,env.numactions,'policytype','egreedy','epsilon',trueepsilon,'gamma',truegamma,'alpha',alphas(i));
    score(i) = agent.imitate_run(trace);
end
plot(alphas,exp(score));
title(sprintf('Likelihood of a trace with gamma %.1f,alpha %.1f being generated by alpha x',truegamma,truealpha))
xlabel('Alphas')
ylabel('Pr(trace)')
saveas(gcf,sprintf('img\\alphas_epsilon.jpg'));
%% Alpha local analysis - Softmax
clear
[model, sim, env ] = games.get(2,1);
truegamma=0.5;
truealpha=0.2;
truetemperature=10;
agent = agents.discrete.get('sarsa',env.numstates,env.numactions,'policytype','softmax','temperature',truetemperature,'gamma',truegamma,'alpha',truealpha);
[ trace policytrace ] = analyse.sampling.synthetic_traces( agent, sim, 300 );
alphas=linspace(0,1,100);
parfor i=1:100
    agent = agents.discrete.get('sarsa',env.numstates,env.numactions,'policytype','softmax','temperature',truetemperature,'gamma',truegamma,'alpha',alphas(i));
    score(i) = agent.imitate_run(trace);
end
plot(alphas,exp(score));
title(sprintf('Likelihood of a trace with gamma %.1f,alpha %.1f being generated by alpha x',truegamma,truealpha))
xlabel('Alphas')
ylabel('Pr(trace)')
saveas(gcf,sprintf('img\\alphas_softmax.jpg'));




%%
clear
[model, sim, env ] = games.get(2,1);
truegammas=[0.5 0.6 0.7];
alphas=[0.05 0.1 0.15 0.2 0.3 0.4];
epsilons=[0.1];
for g=1:length(truegammas)
for a=1:length(alphas)
for e=1:length(epsilons)
agent = agents.discrete.get('sarsa',env.numstates,env.numactions,'policytype','egreedy','epsilon',epsilons(e),'gamma',truegammas(g),'alpha',alphas(a));
[ trace policytrace ] = analyse.sampling.synthetic_traces( agent, sim, 300 );
gammas=linspace(0,1,100);
eps=epsilons(e)
for i=1:100
    agent = agents.discrete.get('sarsa',env.numstates,env.numactions,'policytype','egreedy','epsilon',eps,'gamma',gammas(i),'alpha',alphas(a));
    score(i) = agent.imitate_run(trace);
end
plot(gammas,exp(score));
title(sprintf('Likelihood of a trace with gamma %.1f,epsilon %.1f,alpha%.2f being generated by gamma x',truegammas(g),epsilons(e),alphas(a)))
xlabel('Gammas')
ylabel('Pr(trace)')
saveas(gcf,sprintf('img\\gamma_epsilon0%d_gamma%d_alpha%d.jpg',e,g,a));
plot(gammas,score);
title(sprintf('Log-Likelihood of a trace with gamma %.1f,epsilon %.1f,alpha%.2f being generated by gamma x',truegammas(g),epsilons(e),alphas(a)))
xlabel('Gammas')
ylabel('Pr(trace)')
saveas(gcf,sprintf('img\\gamma_epsilon0%d_gamma%d_alpha%d_log.jpg',e,g,a));
end
end
end



%% Gamma-Alpha local analysis - Egreedy Contour
clear
[model, sim, env ] = games.get(2,1);
truegamma=0.65;
truealpha=0.05;
trueepsilon=0.2;
agent = agents.discrete.get('sarsa',env.numstates,env.numactions,'policytype','egreedy','epsilon',trueepsilon,'gamma',truegamma,'alpha',truealpha);
[ trace policytrace ] = analyse.sampling.synthetic_traces( agent, sim, 300 );
gammas=linspace(0,1,100);
alphas=linspace(0,1,100);
parfor i=1:100
    for j=1:100
        agent = agents.discrete.get('sarsa',env.numstates,env.numactions,'policytype','egreedy','epsilon',trueepsilon,'gamma',gammas(i),'alpha',alphas(j));
        score(i,j) = agent.imitate_run(trace);
    end
end
contourf(gammas,alphas,score)
title(sprintf('Likelihood of a trace with gamma %.1f,epsilon %.1f being generated by gamma x',truegamma,trueepsilon))
xlabel('Alphas')
ylabel('Gammas')
% saveas(gcf,sprintf('img\\gamma_egreedy.jpg'));


% %%
% clear
% [model, sim, env ] = games.get(2,1);
% truegamma=0.5;
% truealpha=0.2;
% temperatures=[5 10 15 20 25 30];
% for e=1:length(temperatures)
% agent = agents.discrete.get('sarsa',env.numstates,env.numactions,'policytype','softmax','temperature',temperatures(e),'gamma',truegamma,'alpha',truealpha);
% [ trace policytrace ] = analyse.sampling.synthetic_traces( agent, sim, 300 );
% gammas=linspace(0,1,100);
% for i=1:100
%     agent = agents.discrete.get('sarsa',env.numstates,env.numactions,'policytype','softmax','temperature',temperatures(e),'gamma',gammas(i),'alpha',truealpha);
%     score(i) = agent.imitate_run(trace);
% end
% plot(gammas,exp(score));
% title(sprintf('Likelihood of a trace with gamma 0.5,temperature %.1f being generated by gamma x',temperatures(e)))
% xlabel('Gammas')
% ylabel('Pr(trace)')
% saveas(gcf,sprintf('img\\gamma_temperature%d.jpg',e));
% end